version: '2'
services:
  web:
    build: ./docker/php
    volumes:
      - ${WEB_ROOT_PATH}:/var/www/html/
      - ./secrets:/secrets/
    ports:
      - '${WEB_PORT}:8080'
    working_dir: ${WEB_WORKING_DIR}
    depends_on:
      - mysql
    networks:
      - oop-week-network


  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ${MYSQL_PATH}:/var/lib/mysql
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - oop-week-network

networks:
  oop-week-network:
    driver: bridge
